### ISSUE TITLE
Endpoints declaratively specified should be checked in status

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1091]
Currently the status check for address spaces do not check endpoints for readiness. This is currently not possible, since the declarative description of the endpoints is changed based on actual state. Instead, I think it would be better to introduce a .status.endpoints which contains the 'actual' status of endpoints (with just name, host, and port) ,and update the readiness check in address controller to check that this list of endpoints matches that in the declarative section.

**Comment by lulf** [comment]
Example:

```
kind: AddressSpace
apiVersion: enmasse.io/v1
metadata:
  name: myspace
spec:
  type: standard
  plan: unlimited-standard
  endpoints:
    - name: messaging
      service: messaging
      cert:
        provider: selfSigned

status:
  isReady: true
  endpoints:
    - name: messaging
      host: messaging.example.com
      port: 5671
```

**Comment by lulf** [comment]
You would also be able to specify the host and port in the .spec.endpoints if you have a specific host you want to use.

**Comment by lulf** [comment]
Updated proposal:
```
kind: AddressSpace
apiVersion: enmasse.io/v1alpha1
metadata:
  name: myspace
spec:
  type: standard
  plan: unlimited-standard
  endpoints: // OPTIONAL: Allows control over which endpoints to expose externally and how they are configured
    - name: messaging
      service: messaging
      externalHost: messaging.example.com // OPTIONAL! Autogenerate possible on OpenShift
      cert:
        provider: selfSigned

status:
  isReady: true
  endpoints:
    - name: messaging
      external:
        host: messaging.example.com
        port: 443
      internal:
       host: messaging.myproject-myspace.svc
       ports:
         - name: amqps
           port: 5671
         - name: amqp
           port: 5672
```
