### ISSUE TITLE
Address created via 'oc' command can't be removed via api-server

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1380]
**Description:**
we have 2 addresses (myqueue1 and myqueue2) created via 'oc' command, then first of them is removed via web console and second one via REST-API. Second address is not removed, however in api-server is information that DELETE was processed. `2018-06-19 10:25:14 INFO HTTPServer:98 - Request DELETE /apis/enmasse.io/v1alpha1/namespaces/myproject/addressspaces/crd-address-test-shared/addresses/myqueue2`

automated test is located in **crd-tests** branch (currently disabled)
```
DISPLAY=:10 make REGISTER_API_SERVER=true STORE_SCREENSHOTS=true  MULTITENANT=true OPENSHIFT_PROJECT="myproject" SYSTEMTEST_ARGS='CustomResourceDefinitionAddressesTest#testAddressCreateViaCmdRemoveViaAgentApi' systemtests
```
myqueue1
```
{"apiVersion":"enmasse.io/v1alpha1","kind":"Address","metadata":{"name":"crd-address-test-shared.myqueue1"},"spec":{"address":"myqueue1","type":"queue","plan":"brokered-queue"}}
```
myqueue2
```
 ---
apiVersion: "enmasse.io/v1alpha1"
kind: "Address"
metadata:
  name: "crd-address-test-shared.myqueue2"
spec:
  address: "myqueue2"
  type: "queue"
  plan: "brokered-queue"
```
Unfortunately I was able to found no errors
