### ISSUE TITLE
Improve configuration flexibility for creating address space endpoints

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1668]
## why

The following use cases should be configurable when creating an address space:

* Specify the certificate to be used for the endpoint
* Specify if an endpoint should expose a route, ingress, nodeport or loadbalancer service
* Specify annotations on the load balancer service when running on AWS
* Specify if a route should use passthrough or reencrypt in the case of https endpoints
* Use OpenShift Cluster CA for all endpoint certs

Today's format for `AddressSpace`:

```
apiVersion: enmasse.io/v1alpha1
kind: AddressSpace
metadata:
  name: myspace
spec:
   ...
   endpoints:
     - name: messaging
       service: messaging
       host: // optional
       servicePort: amqps
       cert: // optional
         provider: self-signed
     - name: console
       service: console
       servicePort: https
       cert:
         provider: self-signed
```

## Proposal

Proposed change to the `AddressSpace` resource:
* Introduce a `certBundle` cert provider to be able to input the cert to be used in a base64 encoded form
* Introduce an 'expose' field to provide more fine-grained control on the form of exposing (route  or loadbalancer + their settings)
* Add 'openshift' cert provider to use the builtin openshift cluster CA for creating certs. This is mainly useful for non-exposed endpoints

Example resource:

```
apiVersion: enmasse.io/v1alpha1
kind: AddressSpace
metadata:
  name: myspace
spec:
   ...
   endpoints:
     - name: messaging
       service: messaging
       cert:
         provider: certBundle
         key: // Base64 encoded cert private key
         cert: // Base64 encoded cert public key
       expose:
         type: route // can be 'route' or 'loadbalancer'
         annotations: // annotations on the route or loadbalancer created
         routeHost: // optional, only relevant for 'route' and 'ingress'
         routeServicePort: // required for 'route' type
         routeTlsTermination: passthrough // required for 'route' type
        
         loadBalancerServicePorts: // Only for loadbalancer type
          - amqp
          - amqps
         loadBalancerSourceRanges: // Optional, only for loadbalancer type
           - ip1
           - ip2
     - name: console
       service: console
       expose:
         type: route
         routeTlsTermination: reencrypt      
         routeServicePort: https
```

Defaults will stay as today.

## Testing

What is the test plan for the feature/change?  

## Documentation

What documentation will be created for this feature? 

## Tasklist

- [x] Introduce a `certBundle` cert provider to be able to input the cert to be used in a base64 encoded form
- [x]  Introduce an 'expose' field to provide more fine-grained control on the form of exposing (route  or loadbalancer + their settings)
- [x] Add 'openshift' cert provider to use the builtin openshift cluster CA for creating certs. This is mainly useful for non-exposed endpoints
