### ISSUE TITLE
Network policies for address spaces

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2000]
## why

Kubernetes supports creating NetworkPolicy resources to control who can send/recv traffic to/from namespaces. For an EnMasse service admin, it is desirable to configure network policies for the created infrastructure. I.e only allow send/recv traffic to the infrastructure related to the address space endpoints.

See https://kubernetes.io/docs/concepts/services-networking/network-policies/ for more information about network policies in Kubernetes.

## Proposal

The StandardInfraConfig and BrokeredInfraConfig resources should be extended to allow network policy to be defined. One important question for discussion, is the granularity of what we would allow. The finer granularity, the more complex it will be, but it will also allow for more flexible policies. Since an advanced policy would need to have knowledge of the UUID assigned to the labels of the infra when creating the policy, some care needs to be taken.

The answer could be to design something that allow both the simple and the advanced form to be specified. For the below simple alternative,  one alternative is to use the `none` policy and require the policies to be created explicitly to get the advanced features.

#### Simplest

The simplest alternative is to add another field `networkPolicy` indicating what network policy to apply to the created infrastructure. Example:

```
kind: StandardInfraConfig
...
spec:
  networkPolicy: none | allowAll | ownerOnly
```

* none - don't create any network policies and rely on the cluster defaults
* allowAll - create policies that allow all address spaces to be accessed from all other namespaces
* ownerOnly - create network policies so that only the namespace where address space resource is created can access the namespace

The policy can be overridden when creating the address space in the same manner:

```
kind: AddressSpace
...
spec:
  networkPolicy: none | allowAll | ownerOnly
```

#### Advanced

The other extreme is flexible but also less user-friendly alternative is to expose more details of the underlying `NetworkPolicy` resource. The syntax could then look something like (with ${INFRA_UUID} being some kind of templating parameter we require to be set to match the infrastructure):

```
kind: StandardInfraConfig
...
spec:
  networkPolicies:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: test-network-policy
      spec:
        podSelector:
          matchLabels:
            role: router
            infraUuid: ${INFRA_UUID}
        policyTypes:
        - Ingress
        - Egress
        ingress:
        - from:
          - ipBlock:
              cidr: 172.17.0.0/16
              except:
              - 172.17.1.0/24
          - namespaceSelector:
              matchLabels:
                project: myproject
          - podSelector:
              matchLabels:
                role: myapp
          ports:
          - protocol: TCP
            port: 6379
        egress:
        - to:
          - ipBlock:
              cidr: 10.0.0.0/24
          ports:
          - protocol: TCP
            port: 5978
```

## Testing

* Deploy an OpenShift cluster with ovs-networkpolicy plugin enabled
* Create infra resources with different network policy types
* Ensure only allowed address spaces are allowed to access endpoints

## Documentation

* Service admin guide should have instructions on the network policy settings

## Tasklist

Enumerate the tasks required to complete the feature

**Comment by rgodfrey** [comment]
Personally I'd be happy with the "simplest" proposal - though is this really a per config or a per addressspace thing (with the infra config really only providing a default) ?

**Comment by rgodfrey** [comment]
>  Question is: Should one be allowed to set a less-secure policy than the one configured by the service admin? My initial feeling is "no", and that one can only set a stricter policy than the default. 

I'm not sure that this is just a strict security thing... Especially if the addressspace owner can still create a route anyway (which effectively allows anyone to make a connection to the endpoint).  As such I'd be tempted to say that the default can always be overridden by the addressspace owner, so the system admin can make "ownerOnly" the default, but an individual app can decide to allow all.

**Comment by lulf** [comment]
@rgodfrey Ok, so the initial syntax might be too simplistic for the ownerOnly policy. Basically the matching rules require either to match on pod labels or namespace labels. On OpenShift instance, users are not allowed to label their namespaces by default, so I'm thinking maybe we should support a subset of the NetworkPolicy syntax of the :

```
networkPolicy:
  from:
    - namespaceSelector:
        matchLabels:
           user: alice
      podSelector:
       matchLabels:
           role: db
  to:
    - namespaceSelector:
        matchLabels:
           user: alice
     - podSelector:
       matchLabels:
           role: db
```

See https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors for more info about this.
