### ISSUE TITLE
WebConsole: incomplete certificate chain 

### ISSUE THREAD

**Issue by famartinrh** [EnMasseProject/enmasse#2427]
**Describe the bug**
When specifying certificate provider for endpoints in address space the server exposing web console shows an incomplete certificate chain. 
This happens for selfsigned and certBundle cert providers exposing endpoints thorugh openshift passthrough routes.
Given this it's not possible to successfully connect to the web console while trusting the CA that generated the certificate serving SSL in this web page

**To Reproduce**
There are tests in systemtests to reproduce this issue, can be found in this PR #2412 
`make systemtests SYSTEMTEST_ARGS="io.enmasse.systemtest.common.certs.CertProviderTest#testConsole*"`

This can be also reproduced manually creating an address space with selfsigned cert provider in endpoints, like this:
```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited-with-mqtt
  authenticationService:
    type: standard
  endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: amqps
      cert:
        provider: selfsigned
    - name: mqtt
      service: mqtt
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: secure-mqtt
      cert:
        provider: selfsigned
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: https
      cert:
        provider: selfsigned
```
Given this in a browser the web console certificate looks like this
![image](https://user-images.githubusercontent.com/46371672/54036167-324b5b80-41bb-11e9-9ca4-79a53fd4d0b2.png)
