### ISSUE TITLE
Instruct url info to be put into configmap

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2446]
**Overview**

When following a gitops-model, it is beneficial to get a deterministic URL for endpoints. Although we cannot control the service endpoint names in EnMasse (2 address spaces could end up creating conflicting ones), it would be useful if a tenant can instruct a configmap to be created with the endpoint information (url, ports, CA).

**Design**

The `AddressSpace` resource would be extended to support the following syntax:

```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  endpoints:
  - name: messaging
    service: messaging
    exports/bindings:
      - kind: ConfigMap
        name: myconfig // Requires the 'system:serviceaccount:enmasse-infra:address-space-controller' service account RBAC rule to be created by application owner.
        namespace: mynamespace // Defaults to namespace of address space
      - kind: Secret
        name: mysecret
      - kind: Service
        name: myservice
```

The Secret/ConfigMap will contain the the following fields:

```
data:
  service.host: messaging-....svc
  service.port.amqp: 5672
  service.port.amqps: 5671
  // Following is only populated if endpoint is exposed
  external.host: ...
  external.port.amqps: 443
```

Service format:
```
kind: Service
...
spec:
  type: ExternalName
  # Points to the existing service in the enmasse-infra namespace
  externalName: messaging-....enmasse-infra.svc.cluster.local
  ports:
  - port: 5672
  - port: 5671
```

**Tasklist**

**Comment by lulf** [comment]
@nathan-vp, would love your input on the design of this feature

**Comment by nathan-vp** [comment]
LGTM!

Thought of it, (optionally) creating a service with a freely choosable name in the namespace of the AddressSpace could be enough to satisfy our use case already.

A headless service can point to a service in another namespace.
```
kind: Service
apiVersion: v1
metadata:
  # Freely choosable by the developer via the AddressSpace resource
  name: my-messaging
  # The namespace where the AddressSpace object lives
  namespace: application-namespace
spec:
  type: ExternalName
  # Points to the existing service in the enmasse-infra namespace
  externalName: messaging-cu0h5dqigl.enmasse-infra.svc.cluster.local
  ports:
  - port: 5672
  - port: 5671
```

This works only on the condition that the user does not need the certificate:
- when using the cluster signer (eg OpenShift) via `.spec.endpoints.[].cert.provider.openshift`, in this case the CA bundle is trusted by the application Pods
- when providing the certificate manually via `.spec.endpoints.[].cert.provider.certBundle`, in this case the developer can bootstrap the Pods with the correct CA bundle

Are there use cases where putting all the other information in a configmap or secret might be helpful? In that case your approach is better.
