### ISSUE TITLE
Allow changing address plans credits for supported address types

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2480]
**Overview**

At present, if it is desirable to change the credits in an address plan, one has to create a new plan, and replace/patch all addresses to use the new plan. 

For the standard address space, it would be very convenient if EnMasse supported changing the credits of existing plans, for those address types that supports it: anycast, multicast and queue.

At present, the 'desired' plan is stored in .spec.plan, whereas the 'applied plan' is stored in an annotation.

**Design**

To support changing the credits of a plan, more information about the plan needs to be embedded into the 'applied plan' information, in the same way as infra configs.

In addition, rather than modifying the existing annotation, a new annotation could be used, but it would be even better if we can make this 'applied plan' info part of .status. Following format could be used:

```
kind: Address
spec:
  plan: small-queue
status:
  isReady: true
  phase: Active
  plan:
    name: large-queue
    resources:
      broker: 1.0
      router: 0.1
``` 

Adding this info would allow the standard-controller to decide if the credits of a desired vs. actual plan has changed, and initiate the same migration logic as done when the plan name changes.
