### ISSUE TITLE
AddressSpace console does not load with custom endpoint

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2855]
**Describe the bug**
I created addressspace with custom external endpoints messaging and mqtt enpoints work but console doesn't.

**To Reproduce**
1. create addressspace CR with custom external endpoints
2. create addressspace
3. open console

definition
```
...
.addNewEndpoint()
.withName("test-enpoint-console")
.withService("console")
.editOrNewExpose()
.withType(ExposeType.route)
.withRouteTlsTermination(TlsTermination.reencrypt)
.withRouteServicePort("https")
.endExpose()
.endEndpoint()
...
```

oc get addressspace standard -o yaml
```
...
- externalHost: test-endpoint-console-lfjl6yepc1-myproject.<ip-addr>.nip.io
    externalPorts:
    - name: https
      port: 443
    name: test-endpoint-console
    serviceHost: console-lfjl6yepc1.myproject.svc
    servicePorts:
    - name: https
      port: 8081
...
```
![obrazek](https://user-images.githubusercontent.com/11318335/58656322-5c28a000-831c-11e9-906c-5999480362b2.png)
