### ISSUE TITLE
OLM example addressspace can't be created

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2928]
**Describe the bug**
example addressspace from OLM can't be created because of missing auth service

**To Reproduce**
1. Install enmasse using OLM
2. Open installed operators
3. Select address space
4. Try to create example

I suggest to update example and add none-authservice which is an example in authentication service.

current example:
```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
  namespace: openshift-operators
spec:
  plan: standard-small
  type: standard
```

suggestion
```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
  namespace: openshift-operators
spec:
  plan: standard-small
  type: standard
  authneticationservice:
    name: none-authservice
```
