### ISSUE TITLE
Cannot create new address in EnMasse on Openshift 4.0

### ISSUE THREAD

**Issue by astoycos** [EnMasseProject/enmasse#3741]
**Describe the bug**

When Trying to Create a new address in EnMasse 0.30.1 on Openshift 4.0 The following error is observed in both the console and command line
 
`Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps "enmasse-infra.iot.event" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>`

Even though I gave all the service accounts in the namespace enmasse-infra the ability to make new addresses 

![image](https://user-images.githubusercontent.com/23533892/73033729-e4f6cd80-3e10-11ea-848c-d4add12d90a7.png)
![image](https://user-images.githubusercontent.com/23533892/73033738-e9bb8180-3e10-11ea-9adf-fbe756e8d1ac.png)

I also attached the logs from the API server pod that is spun up as part of the Enmasse Operator, which shows in more detail the above error
[logs.txt](https://github.com/EnMasseProject/enmasse/files/4106189/logs.txt)

**To Reproduce**
1. Startup a normal Openshift 4 cluster 
2. Download and install the EnMasse operator from the Operator.io hub or download following command line documentation to a project titled "enmasse-infra"  
3. Run the "quick start infrastructure" script as explained in the documentation 
4. Make a new Address Space titled "iot" with either console or command line 
5. Try and make a new address in the space you just created, with either console or command line to recreate error.

**Expected behavior**
A new address to be created 

**Screenshots**

**Additional context**
This is just in an attempt to follow the quick start documentation to get Enmasse up and running

**Comment by lulf** [comment]
@astoycos Thanks for reporting the issue. This looks like a known issue with version 0.30.1, which was missing a permission for setting configmap finalizers for the api-server service account. This is fixed in 0.30.2, but the PR to include this in OperatorHub.io has not yet been merged. To work around this, apply the following (replacing $NAMESPACE with the namespace where you installed the operator):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:api-server-fix
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "configmaps/finalizers" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-fix
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:api-server-fix
subjects:
- kind: ServiceAccount
  name: api-server
  namespace: ${NAMESPACE}
```
