### ISSUE TITLE
Address links not displayed if address resource name suffix does not match address name

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4287]
**Describe the bug**

If your address's resource name  does not match the actual messaging address name, the addresses's link(s) are not displayed in the console.

**To Reproduce**
1. Create an address resource like so (notice the difference in the pluralisation):

```
kind: Address
metadata:
  name: widgetspace.fabricate-request
spec:
  address: fabricate-requests
  plan: standard-small-queue
  type: queue

```
2. Create a sending and receiving link to the address.
3. Log on to the Console and navigate to the address's links.

**Expected behavior**

The two links should be seen.

**Additional context**
Examining the graphql, it appears that the issue is server side.
