### ISSUE TITLE
Some changes to an address space's endpoints aren't reflected accurately

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4352]
**Describe the bug**

Whilst testing mutating an address space's endpoint configuration I notice what appears to be unintended behaviour.

1. Adding an a new OpenShift endpoint to an existing address space with existing self signed endpoints (the default set) does not have the desired effect.  A new route is created, but it does not present an OpenShift certificate.  Instead it presents the same self signed cert of the existing endpoints.

```
   - name: messaging-os
      service: messaging
      cert:
        provider: openshift
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: amps
```
2. Removing the default provided set of endpoints  doesn't work.  The system automatically recreates the default set.  This would affect a UI workflow where a user removes all endpoints prior to adding their own.  

3. Replacing the default provided endpoint set  with a new endpoint set (say an openshift endpoint) doesn't work.  The `wss` endpoint disappears correctly,  but the certificate associated with the messaging endpoint remains the self-signed one.

4.  Changing `routeTlsTermination` reencrypt <=> passthrough doesn't update the existing routes.

5. Duplicate endpoint names aren't detected.  I would expect the AddressSpace to flag an error through its status section.

6. Expose type route requires routeServicePort, but this isn't enforced by the CRD
