### ISSUE TITLE
Add support for topics and subscription

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#4469]
**Description**

Add support for topics and subscription

**Comment by lulf** [comment]
In the shared infra design doc, the ability to create 'transactional' queues and topics are indicated by an array of capabilities on the MessagingPlan:

```
kind: MessagingPlan
spec:
  capabilities:
  - transactional
```

In addition to enforcing this at the messaging plan, I wonder if it should be possible to specify this property on the `MessagingTenant` as well. This allows making use of transactional addresses without having to create a MessagingPlan. It could be exposed like this:

```
kind: MessagingTenant
spec:
  # For user setting the capability
  capabilities:
  - transactional
status:
  # The capabilities as inferred by the operator, either based on plan or on the setting in the spec.
  capabilities:
  - transactional
```

*Question 1*: Should it be possible to override the plan in this regard? 

If a `MessagingTenant` has the transactional capability, the `MessagingAddress` controller can:

* Use a 'transactional scheduler' to enforce all addresses for that tenant to be created on the same broker
* Configure the linkRoute in the router for all addresses with prefix of the tenant namespace

I think the simplest way to implement this in the operator is to create this link route when the first address is created belonging to a tenant with transactional capability is created. Once that address has been scheduled, the operator can then know what parameters the linkRoute should have.

*Question 2*: Does this sufficiently cover the use cases of a JMS/Transactional broker? I.e. do we need to allow clients to use this virtual broker without any addresses configured?

@k-wall @rgodfrey Any concerns/comments to this?
