### ISSUE TITLE
Extend addressspaceschema to enumerate endpoint types and certification providers

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4590]
**Description**

The Console UI needs sufficient information from the server side to drive the address space creation workflow.  For 0.32, the workflow will be extended to allow the user to configure endpoints.

The availability of endpoints and cert providers differs between Kubernetes and OpenShift.
The route service port descriptions will differ between standard and brokered (specially the description will enumerate all supported protools which for brokered will include CORE, OpenWire, MQTT, STOMP)

This solution will be for 0.32 only.  Standard MQTT support is out of scope.

**Design**

```
routeServicePorts:
  - name: amqps
     displayName: "Messaging (AMQP)"
     routeTlsTerminations: ['passthrough']
  - name: https
     displayName: "Websocket messaging (AMQP-WS)
     routeTlsTerminations: ['passthrough', 'reencrypt']
certificateProviderTypes:
  - name:  openshift
     displayName: "OpenShift"
     description: "OpenShift provides a TLS certificate"
  - name: selfsigned
    displayName: "Selft-signed"
    description: "System generates self-signed TLS certificate"
  - name: certBundle
    displayName: "Certificate Bundle"
    description: "Upload a TLS certificate bundle"
endpointExposeTypes:
   - name: route
      displayName: "OpenShift Route"
      description: "OpenShift Route"
   - name: loadbalancer
      displayName: "LoadBalancer service"
      description: "LoadBalancer service"
```
**Tasklist**

Enumerate the sub-tasks required to complete the task:

* [x] Extend the schema to encapsulate certificate providers and available endpoint types with descriptions.
* [x] Java implementation
* [x] Go implementation and the GraphQL layer
* [x] Mock
