### ISSUE TITLE
AddressSpaces CRD reported as NonStructuralSchema true

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4604]
**Describe the bug**

Kuberenets reports that the AddressSpaces CRD is NonStructuralSchema.

```
  conditions:
  - lastTransitionTime: "2020-05-14T10:27:30Z"
    message: '[spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[0].properties[value].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[0].properties[value].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[0].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].properties[key].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].properties[key].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].properties[name].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].properties[name].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].properties[valueFromSecret].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].anyOf[1].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[password].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[0].properties[value].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[0].properties[value].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[0].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].properties[key].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].properties[key].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].properties[name].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].properties[name].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].properties[valueFromSecret].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].anyOf[1].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[credentials].properties[username].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[0].properties[value].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[0].properties[value].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[0].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].properties[key].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].properties[key].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].properties[name].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].properties[name].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].properties[valueFromSecret].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].anyOf[1].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[caCert].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[0].properties[value].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[0].properties[value].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[0].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].properties[key].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].properties[key].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].properties[name].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].properties[name].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].properties[valueFromSecret].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].anyOf[1].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientCert].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[0].properties[value].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[0].properties[value].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[0].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].properties[key].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].properties[key].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].properties[name].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].properties[name].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].properties[valueFromSecret].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].anyOf[1].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[connectors].items.properties[tls].properties[clientKey].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[annotations].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[loadBalancerPorts].items.type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[loadBalancerPorts].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[loadBalancerSourceRanges].items.type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[loadBalancerSourceRanges].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[type].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[0].properties[type].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[annotations].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[annotations].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[routeHost].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[routeServicePort].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[routeServicePort].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[routeTlsTermination].type:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[type].description:
      Forbidden: must be empty to be structural, spec.validation.openAPIV3Schema.properties[spec].properties[endpoints].items.properties[expose].anyOf[1].properties[type].type:
      Forbidden: must be empty to be structural]'
    reason: Violations
```

**To Reproduce**
1. Run `oc get crd  -o yaml addressspaces.enmasse.io`
2. Observe the output of the status section

**Expected behavior**

**Screenshots**

**Additional context**
