### ISSUE TITLE
EnMasse CSV sticks at Pending since OpenShift 4.4.11

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#5001]
**Describe the bug**

On the latest releases of OpenShift, EnMasse (0.32, 0.31) fails to install from OLM owing to the following OpenShift defect.

https://bugzilla.redhat.com/show_bug.cgi?id=1855088
https://bugzilla.redhat.com/show_bug.cgi?id=1856413

```
CSV Status sticks at "Pending" rather than "Succeeded"

 - dependents:
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list","watch"],"apiGroups":["iot.enmasse.io"],"resources":["iotprojects"]}
      status: NotSatisfied
      version: v1beta1
    group: ""
    kind: ServiceAccount
    message: Policy rule not satisfied for service account
    name: iot-tenant-service
    status: PresentNotSatisfied
```

**To Reproduce**
https://bugzilla.redhat.com/show_bug.cgi?id=1856413

**Expected behavior**
Install should succeed.

**Screenshots**

**Additional context**
