### ISSUE TITLE
Support configuring external loadbalancer annotations and properties in endpoints

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#661]
The current configuration settings for address space endpoints do not provide sufficient flexibility in configuring load balancer settings for cloud providers such as AWS. As part of creating an address space, one should be able to configure the necessary aspects of a service. Example service:

```
apiVersion: v1
     kind: Service
     metadata:
       labels:
         app: enmasse
       annotations:
         dns.alpha.kubernetes.io/external: our-messaging-domain-name.
         service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "certName"
         service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "5671"
       name: messaging-external
     spec:
       ports:
       - name: amqps
         port: 5671
        protocol: TCP
         # TLS gets terminated at the LoadBalancer, target port here 5672
         targetPort: 5672
       selector:
        capability: router
       type: LoadBalancer
        loadBalancerSourceRanges: ..ip list..
```
