### ISSUE TITLE
Using qdstat/qdmanage with plain SASL auth doesn't work

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#789]
When using the qdstat tool to query the dispatch router like this
`qdstat -a --sasl-username=user --sasl-password=pw --sasl-mechanisms=PLAIN -b amqps://192.168.99.100:30071`
I get the error
`LinkDetached: sender 720d2bf2-e2f1-44f5-aa63-19aaaefffa13-$management to $management closed due to: Condition('amqp:unauthorized-access', 'link disallowed by local policy')`
So far that is expected as the user isn't in any "send/recv_[*]" Keycloak groups.

But after having assigned Keycloak groups `send_%24management` and `recv_%24management` (ie. send/recv_$management) to the user, there still is the error
`LinkDetached: receiver ab1c4941-1d8e-4b6a-901d-7f2dcb3c1955-a9ee7336-0a32-4877-90b8-2cc0aba75067 from None closed due to: Condition('amqp:unauthorized-access', 'link disallowed by local policy')`

Also assigning the groups `send_%2A` and `recv_%2A` (for send/recv_*) doesn't help.

**Comment by grs** [comment]
Just assign the literal send_*/recv_* groups, without the url escapes.

**Comment by calohmn** [comment]
@grs did a test with `send/recv_*` and still got the above error (using current state of master).

**Comment by grs** [comment]
@calohmn which interface in the router are you connecting to, do you know? I don't recognise the port number.

**Comment by calohmn** [comment]
@grs That's the amqps port of the "messaging-external" service.
We are not using the original "messaging-external" service created by EnMasse but create our own (because we need extra AWS-related annotations).
In our minikube-environment, we use this yml fragment:
````
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
      type: loadbalancer
    annotations:
      addressSpace: default
      io.enmasse.certSecretName: external-certs-messaging
      io.enmasse.serviceName: messaging
    name: messaging-external
  spec:
    ports:
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: 5671
      nodePort: 30071
    selector:
      capability: router
    type: NodePort
    sessionAffinity: None
    externalTrafficPolicy: Cluster
````
